services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - backend-logs:/app/logs
    environment:
      LOG_LEVEL: DEBUG
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
