/* eslint-disable */
/* prettier-ignore */
// This file is auto-generated by TanStack Router

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as AuthImport } from "./routes/auth";
import { Route as SyncImport } from "./routes/sync";
import { Route as VisualImport } from "./routes/visual";
import { Route as ReportImport } from "./routes/report";
import { Route as StatusImport } from "./routes/status";

const IndexRoute = IndexImport.update({ path: "/", getParentRoute: () => rootRoute } as never);
const AuthRoute = AuthImport.update({ path: "/auth", getParentRoute: () => rootRoute } as never);
const SyncRoute = SyncImport.update({ path: "/sync", getParentRoute: () => rootRoute } as never);
const VisualRoute = VisualImport.update({ path: "/visual", getParentRoute: () => rootRoute } as never);
const ReportRoute = ReportImport.update({ path: "/report", getParentRoute: () => rootRoute } as never);
const StatusRoute = StatusImport.update({ path: "/status", getParentRoute: () => rootRoute } as never);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": { parentRoute: typeof rootRoute };
    "/auth": { parentRoute: typeof rootRoute };
    "/sync": { parentRoute: typeof rootRoute };
    "/visual": { parentRoute: typeof rootRoute };
    "/report": { parentRoute: typeof rootRoute };
    "/status": { parentRoute: typeof rootRoute };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthRoute,
  SyncRoute,
  VisualRoute,
  ReportRoute,
  StatusRoute,
]);
